Add x264+AAC encoding to ~/.bin/j

diff --git a/.bin/j b/.bin/j
--- a/.bin/j
+++ b/.bin/j
@@ -28,10 +28,16 @@ chkdeps()
 	which grep		|| die "no grep"
 	which sed		|| die "no sed"
 	which jhead		|| die "no jhead"
-	which ffmpeg	|| die "no ffmpeg"
+	which avconv	|| die "no avconv"
 	which head		|| die "no head"
 	which tr		|| die "no tr"
 	which gm		|| die "no gm"
+	which sox		|| die "no sox"
+	which normalize-audio	|| die "no normalize-audio"
+	which neroAacEnc	|| die "no neroAacEnc"
+	which x264		|| die "no x264"
+	which MP4Box	|| die "no MP4Box"
+	which cptime	|| die "no cptime"
 }
 
 chkdeps >/dev/null
@@ -132,8 +138,7 @@ USAGE="usage: $0 <mode>[ <param>] <file1>[ <file2>[ ...]]
   renmov        mv \$name.(avi|mp4|...) to (\$mod_time - \$duration).\$ext
   res           -quality 80
   res2          -resize 50% -quality 60, progressive optimization
-  xvid <brate> [-rot]  convert to XviD (2-pass, bitrate=\$brate kb/s)
-                       + MP3 (128 kb/s) [opt.: rotate 90 CW]"
+  x264          convert any video format to x264+AAC (playable on _everything_)"
 
 test $# -gt 0 -a "${1}" != "-h" -a "${1}" != "--help" || die "${USAGE}"
 test $# -gt 1 || die "error: no files to process"
@@ -344,7 +349,7 @@ case $OPMODE in
 
 			EXT=$(echo "${1}" | grep -Po '\.[^.]+$' | tr -s '[A-Z]' '[a-z]')
 
-			R=$(ffmpeg -i "${1}" 2>&1 | grep creation_time)
+			R=$(avconv -i "${1}" 2>&1 | grep creation_time)
 			test $? -eq 0 || die "error: creation_time not found"
 
 			CTIME=$(echo "${R}" | sed -e 's/[^0-9]//g' | sed -re 's/(........)(......)$/\1-\2/' | head -n 1)
@@ -367,7 +372,7 @@ case $OPMODE in
 		while [ $# -gt 0 ] ; do
 			hlpr_header "${1}"
 
-			R=$(ffmpeg -i "${1}" 2>&1 | grep -Po 'Duration: \d\d:\d\d:\d\d')
+			R=$(avconv -i "${1}" 2>&1 | grep -Po 'Duration: \d\d:\d\d:\d\d')
 			test $? -eq 0 || die "error: Duration not found"
 
 			DUR=$(echo "${R}" | sed -e 's/[^0-9]//g' | sed -re 's/^(..)(..)(..)$/\1 * 3600 + \2 * 60 + \3/' | bc)
@@ -445,6 +450,54 @@ case $OPMODE in
 
 			hlpr_optimize -p "${1}"
 			hlpr_setftime "${1}"
+
+			echo
+			shift
+		done
+		;;
+
+	x264)
+		while [ $# -gt 0 ] ; do
+			hlpr_header "${1}"
+
+			FILE=$(echo "${1}" | sed -re 's/\//\\\\/g')
+			if [ -n "$(echo "${FILE}" | grep -P '\.mp4$')" ] ; then
+				ORIG=$(echo "${FILE}" | sed -re 's/(\.[^\.]*)$/-original\1/')
+				echo "-- renaming input to ${ORIG}"
+				mv -v "${FILE}" "${ORIG}" || die "error: unable to mv"
+			else
+				ORIG="${FILE}"
+			fi
+			BASE=$(echo "${FILE}" | sed -re 's/\.[^\.]*$//')
+
+			echo "-- extracting audio as PCM S16LE WAV"
+			avconv -threads 4 -i "${ORIG}" -vn -acodec pcm_s16le "${BASE}-audio-preres.wav" || die "error: avconv"
+
+			echo "-- resampling audio to 48000 Hz"
+			sox "${BASE}-audio-preres.wav" -V -e signed-integer -r 48000 "${BASE}-audio.wav" || die "error: sox"
+			rm -v "${BASE}-audio-preres.wav" || die "error: unable to rm extracted audio"
+
+			echo "-- normalizing audio (stay calm, using peak value!)"
+			normalize-audio --peak "${BASE}-audio.wav" || die "error: unable to normalize-audio"
+
+			echo "-- compressing audio using AAC encoder by Nero"
+			neroAacEnc -if "${BASE}-audio.wav" -of "${BASE}-audio.mp4" || die "error: unable to compress audio"
+			rm -v "${BASE}-audio.wav" || die "error: unable to rm normalized audio"
+
+			echo "-- compressing video using x264 (level 3.1)"
+			x264 --preset veryslow --tune film --crf 25 --vbv-maxrate 17500 --vbv-bufsize 17500 --level 3.1 -o "${BASE}-video.mp4" "${ORIG}" || die "error: x264 failed"
+
+			echo "-- adding video to MP4 container"
+			MP4Box -add "${BASE}-video.mp4" "${BASE}.mp4" || die "error: MP4Box failed"
+
+			echo "-- adding audio to MP4 container"
+			MP4Box -add "${BASE}-audio.mp4" "${BASE}.mp4" || die "error: MP4Box failed"
+
+			rm -v "${BASE}-audio.mp4" || die "error: removing tmp audio failed"
+			rm -v "${BASE}-video.mp4" || die "error: removing tmp video failed"
+
+			echo "-- copying original timestamp"
+			cptime "${ORIG}" "${BASE}.mp4" || die "error: cptime failed"
 
 			echo
 			shift
